### PR TITLE
Move a few misc items into files

### PR DESCRIPTION
**Pull request by cycomachead**
Feel free to comment if some of this doesn't make sense.
I was feeling like it was a bit hard to find times in app.lua.

### CODE REVIEW

**Comment by bromagosa** [comment]
Which reminds me, I totally had forgotten about this one. Is it still relevant?

**Comment by bromagosa** [comment]
Bump

**Comment by bromagosa** [comment]
Re-bump, now that you're active again :stuck_out_tongue:

**Comment by cycomachead** [comment]
Oh well this definitely needs to be redone too many conflicts. Nothing’s major though so it can wait.

**Pull request closed without merging**
