### PR TITLE
Structure Collections API with a Controller

### PR DESCRIPTION
**Pull request by cycomachead**
A first pass at what this might look like.

We'd probably create the following controllers later:
* Users
* Projects
* Remixes

### CODE REVIEW

**Comment by bromagosa** [comment]
Oh noes! I was just doing the same thing!

**Comment by bromagosa** [comment]
But from what I see, mine is more complete (been working on it for a couple hours).

**Comment by bromagosa** [comment]
Closing this since it's now superseded by my recent commits.

I like it better than before, but I think these refactorings could be done in a million different ways and it'd always end up being a matter of personal taste.

Anyway, the structure is cleaner than it was and it accomplishes the goals we wanted:

* Project, User and Collection controllers are in separate files
* All API endpoints are still in a single file and are now much easier to find because of the reduced file length

Let me know if you have any comments. This is deployed to staging and I want to test it for a while before deploying it for real. The changes are relatively trivial but substantial, so it's very possible that I missed something.

**Comment by cycomachead** [comment]
I think this is great. 

A couple things, though. All are pretty minor. 

* there are a couple routes that right now are HTML pages. I don’t think those routes should be part of the API - but I guess they’re going away soon enough. 
* I prefer not nesting under a table but just setting a key. Most of the reasoning is that you get to read a lot more on a line 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by bromagosa** [comment]
> * there are a couple routes that right now are HTML pages. I don’t think those routes should be part of the API - but I guess they’re going away soon enough.

Yep. These will go away soon. Once we deploy the social site, these will just be social site pages.

> * I prefer not nesting under a table but just setting a key. Most of the reasoning is that you get to read a lot more on a line

I don't understand what you're referring to. Is it the `UserController.GET.current_user` structure? I think it's quite clean this way and you always know whether you're adding, getting or removing an element.

**Comment by bromagosa** [comment]
Oh, or do you just mean the declaration style, where you'd prefer something like:

```
function UserController.GET.current_user (self)
  (blah)
end
```

?

**Comment by cycomachead** [comment]
> Oh, or do you just mean the declaration style, where you'd prefer something like:

Sorry, yeah I just meant the declaration. The table/object style has less code, but I find you can get lost as to where you are in a big object.

**Comment by bromagosa** [comment]
Right, that's why I added the `-- METHOD path`  comment at the top of each function, cos I kept forgetting which subtable I was in, but we can change to a more linear style if you want, I've no preferences over this.

**Pull request closed without merging**
