### PR TITLE
Update Configuration For Staging Server

### PR DESCRIPTION
**Pull request by cycomachead**
OK, this is a better attempt at cleaning up the configuration.

* moves nginx.conf files into logical chunks
* reduces the need for SSL in development environments
* adds a staging environment to config.lua
* There's now one *.conf file for each host, so there's a total of 4. Mostly, these just specify the SSL certificates used. I think keeping the file names for certs tracked will be helpful, since it keeps things documented a bit more.

* ~~replaces `../setenv` with a `.env` script. This is a useful standardization, as there are tools like Foreman or Overmind which will use that file when running a local server.~~
* ~~fixes the issue of CORS failing because port 80 is supplied in the snap url on the cloud server.~~

### CODE REVIEW

**Comment by cycomachead** [comment]
I'm going to split this up into smaller chunks. :)

**Comment by cycomachead** [comment]
OK, #73, #74, #75 will make this a bit smaller. I would rank them in that order. #73 fixes an annoyance currently on cloud.snap.berkeley.edu. 

Otherwise, I don't know if there's much else to make this PR smaller. The changes are all related after that.

**Comment by bromagosa** [comment]
Oh I see, you're testing these in the staging server indeed. Sorry, hadn't gotten to this PR yet! :stuck_out_tongue:

I'm guessing this PR is going away after the rest are merged, right?

**Comment by cycomachead** [comment]
This won't totally go away. But it should be a lot smaller. :)

It's mostly going add the config differences for staging, and when that's merged it will remove the need for SSL certs when doing development.

**Pull request merged**
