### PR TITLE
Add testing framework and error handling fixes

### PR DESCRIPTION
**Pull request by aaaschmitt**
- add busted test framework: http://olivinelabs.com/busted/
- add tests for login endpoint
- fix error handling so that yield_error now returns 401 by default and customizable otherwise

### CODE REVIEW

**Comment by bromagosa** [comment]
While I don't dislike Busted per se, I _do_ think adding tests to such a small API is over-engineering. And I come from the Smalltalk world, where TDD was invented and is revered as if it was the holy grail.

This cloud was supposed to stay tiny and it's already grown past what I would have liked it to. Adding a test framework to it will only make things worse and will mean having to maintain both the codebase and the tests. TDD may make sense in big projects that a single person can't understand. In any other case I'm pretty sure one could prove it just helps double development time.

I'll add a `CONTRIBUTE.md` file where we specify what we need help on and what the procedure should be for sending PRs. I'm sorry I haven't done that before... :(

**Comment by cycomachead** [comment]
Looking at this. I definitely think this is helpful. There’s actually very few things to change. 
 
Importantly, the error handling fixes should be merged. Getting errors and responses right definitely makes writing the front end easier and less error prone, even if no one else consumes the API but us.

**Comment by bromagosa** [comment]
Yeah. But since this PR mixes two different things together. I can't pull
the one without the other.

Missatge de Michael Ball <notifications@github.com> del dia dc., 11 de jul.
2018 a les 20:07:

**Comment by cycomachead** [comment]
by the way, If you want to just extract a file, then `git checkout $branch-name -- $file-name` will grab it. 

Otherwise, we chatted a bit and TDD wasn't the intent. They were regression tests, not trying to prescribe anything.

**Pull request closed without merging**
